services:
  mongodb:
    image: mongo:latest
    container_name: cardartvoter-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=cardartvoter

volumes:
  mongodb_data:
